# https://github.com/svg/svgo/blob/master/.svgo.yml
multipass: false
full: true
floatPrecision: 2
plugins:
  - cleanupAttrs: true
  - inlineStyles: true
  - removeDoctype: true
  - removeXMLProcInst: true
  - removeComments: true
  - removeMetadata: true
  - removeTitle: true
  - removeDesc: true
  - removeUselessDefs: true
  - removeXMLNS: false
  - removeEditorsNSData: true
  - removeEmptyAttrs: true
  - removeHiddenElems: true
  - removeEmptyText: true
  - removeEmptyContainers: true
  - removeViewBox: true
  - cleanupEnableBackground: true
  - minifyStyles: true
  - convertStyleToAttrs: true
  - convertColors: true
  - convertPathData: true
  - convertTransform: true
  - removeUnknownsAndDefaults: true
  - removeNonInheritableGroupAttrs: true
  - removeUselessStrokeAndFill: true
  - removeUnusedNS: true
  - prefixIds: false
  - cleanupIDs: true
  - cleanupNumericValues: true
  - cleanupListOfValues: false
  - moveElemsAttrsToGroup: true
  - moveGroupAttrsToElems: true
  - collapseGroups: true
  - removeRasterImages: true
  - mergePaths: true
  - convertShapeToPath: true
  - convertEllipseToCircle: true
  - sortAttrs: true
  - sortDefsChildren: true
  - removeDimensions: false
  - removeAttrs: false
  - removeAttributesBySelector: false
  - removeElementsByAttr: false
  - addClassesToSVGElement: false
  - addAttributesToSVGElement: false
  - removeOffCanvasPaths: true
  - removeStyleElement: true
  - removeScriptElement: true
  - reusePaths: false
js2svg:
  pretty: false
  indent: 2
